version: '3.6'
services:
    db:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_DATABASE: 'carpark_development'
        # So you don't have to use root, but you can if you like
        MYSQL_USER: 'root'
        # You can use whatever password you like
        MYSQL_PASSWORD: ''
        # Password for root access
        MYSQL_ROOT_PASSWORD: 'password'
        # <Port exposed> : < MySQL Port running inside container>
        ports: "3306:3306"
        # Opens port 3306 on the container, 
        expose: '3306'
        # Where our data will be persisted
        volumes: my-db:/var/lib/mysql
    web:
      build: .
      command: puma
      volumes:
        - .:/myapp
      ports:
        - "3000:3000"
      depends_on:
      - db
